#!/bin/bash

#Moze se samo pri upisu podataka koristiti > umjesto >>
function izbrisi_prethodno_dodane_proizvode()
{
    $(truncate -s 0 proizvodi_iz_Konzuma.txt)
    $(truncate -s 0 proizvodi_iz_Kauflanda.txt)
}

function unesi_kljucnu_rijec_pretrazivanja()
{
    kljucna_rijec=$(whiptail --inputbox "\nUnesi naziv proizvoda:" 10 30 jimmy cokolada --title "UNOS PROIZVODA" 3>&1 1>&2 2>&3)
    kljucna_rijec=$(sed "s# #+#g" <<<$kljucna_rijec)
}

function dohvati_podatke_proizvoda_iz_Konzuma_i_Kauflanda()
{
    $(
        curl -s "https://www.konzum.hr/web/search?&search%5Bscope%5D=products&search%5Bterm%5D=$kljucna_rijec&sort=PRICE_ASC" | 
        egrep 'data-ga-name|data-ga-price|data-ga-brand|price--c' | 
        uniq | 
        sed 's#data-ga-name=##g;
        s#"##g;
        s#data-ga-price=##g;
        s#data-ga-brand=##g;
        s#<small class=price--c>##g;
        s#</small>##g' >> proizvodi_iz_Konzuma.txt
    )

    $(
        curl -s "https://www.kaufland.hr/pretrazivanje.html?q=$kljucna_rijec" | 
        egrep -A1 'm-offer-tile__subtitle|m-offer-tile__title|m-offer-tile__quantity|a-pricetag__price' | 
        tr -d '\t' | 
        sed 's#<h5 class="m-offer-tile__subtitle##;
        s#">##;
        s#--##;
        s#</h5>##;
        s#<h4 class="m-offer-tile__title##;
        s#<div class="m-offer-tile__quantity##;
        s#<div class="a-pricetag__price-container##;
        s#<div class="a-pricetag__old-price##;
        s#<div class="a-pricetag__price##;
        s#<span class="a-pricetag__currency kn</span>##;
        s#</div>##' | 
        sed "/^ *$/d" >> proizvodi_iz_Kauflanda.txt
    )
}

function oblikuj_podatke_proizvoda_za_ispis()
{
    atributi_proizvoda=()
    proizvodi=()
    brojac=0
    #Format: [0] naziv, [1] cijena, [2] proizvođač, [3] kn/kg, kn/kom... (4 atributa proizvoda)   
    while read red
    do
        if [ $brojac -eq 4 ]; then
            brojac=0
            #Pretvorba formata iz 9,99 kn u 9.99 kn/kom
            atributi_proizvoda[1]=$(sed "s#,#.#;s# kn# ${atributi_proizvoda[3]}#" <<<${atributi_proizvoda[1]})
            proizvodi+=("${atributi_proizvoda[1]} --- ${atributi_proizvoda[0]} ${atributi_proizvoda[2]} --- Konzum")
        fi
        atributi_proizvoda[$brojac]=$red
        ((brojac++))
    done < proizvodi_iz_Konzuma.txt

    #Format: [0] naziv, [1] dodatan opis proizvoda, [2] količina proizvoda 100g, 1kg..., [3] cijena (4 atributa proizvoda) 
    regularni_izraz_za_cijenu='^[0-9]+([.]((-{1})|([0-9]{2})))?$'
    brojac=0
    while read red
    do
        #Proizvod nekad nema [1] dodatan opis pa pomoću regularnog izraza provjeravam je li zadnji atribut [3] cijena 
        if [ $brojac -eq 4 ] && [[ "${atributi_proizvoda[3]}" =~ $regularni_izraz_za_cijenu ]]; then
            brojac=0
            proizvodi+=("${atributi_proizvoda[3]} kn --- ${atributi_proizvoda[0]} ${atributi_proizvoda[1]} ${atributi_proizvoda[2]} --- Kaufland")
        elif [ $brojac -eq 4 ] && ! [[ "${atributi_proizvoda[3]}" =~ $regularni_izraz_za_cijenu ]]; then
            proizvodi+=("${atributi_proizvoda[2]} kn --- ${atributi_proizvoda[0]} ${atributi_proizvoda[1]} --- Kaufland")
            #Ako zadnji atribut nije cijena, znači da je na [3] zapravo [0] naziv od sljedećeg proizvoda
            brojac=1
            atributi_proizvoda[0]=${atributi_proizvoda[3]}
        #Mogu postojati dvije cijene: regularna i ona uz Kaufland karticu
        #Kombinacija prethodnog i ovog slučaja (nema dodatnog opisa i postoje dvije cijene) pokriva prvi slučaj
        elif [[ "${atributi_proizvoda[3]}" =~ $regularni_izraz_za_cijenu ]] && [[ "${atributi_proizvoda[0]}" =~ $regularni_izraz_za_cijenu ]]; then
            zadnji_proizvod=${proizvodi[-1]}
            zadnji_proizvod=$(sed "s# --- Kaufland# KC cijena: ${atributi_proizvoda[0]} kn --- Kaufland#" <<<$zadnji_proizvod)
            proizvodi[-1]=$zadnji_proizvod
            brojac=0
        fi
        atributi_proizvoda[$brojac]=$red
        ((brojac++))
    done < proizvodi_iz_Kauflanda.txt
}

function sortiraj_proizvode_po_cijeni()
{
    $(printf "%s\n" "${proizvodi[@]}" > svi_proizvodi.txt)
    $(sort -g -t' ' -o svi_proizvodi.txt svi_proizvodi.txt)
    sortirani_proizvodi=()
    while read red
    do
        sortirani_proizvodi+=("$red")
    done < svi_proizvodi.txt
}

function ispisi_proizvode()
{
    brojac=0
    polje=("$@")
    prikaz_proizvoda=()
    for proizvod in "${polje[@]}"
    do
        ((brojac++))
        prikaz_proizvoda+=("$brojac" "$proizvod")
    done
    odabrani_proizvod=$(
        whiptail --title "PROIZVODI" --menu "\nOdaberi proizvod za košaricu:" 25 135 15 \
        "${prikaz_proizvoda[@]}"  3>&2 2>&1 1>&3	
    )
    #Cancel -> 1, ESC key -> -1, OK ili ako je odabran proizvod -> 0
    exitstatus=$?
}

function dodaj_odabrani_proizvod_u_kosaricu()
{
    (( pozicija_odabranog_proizvoda=odabrani_proizvod-1 ))
    shopping_lista+=("${sortirani_proizvodi[$pozicija_odabranog_proizvoda]}")
}

function razdvoji_proizvode()
{
    proizvodi_iz_Konzuma=()
    proizvodi_iz_Kauflanda=()
    for proizvod in "${shopping_lista[@]}"
    do
        trgovina=$(echo "$proizvod" | awk '{print $NF}')
        case $trgovina in
            "Konzum")
                proizvodi_iz_Konzuma+=("$proizvod")
            ;;
	        "Kaufland")
                proizvodi_iz_Kauflanda+=("$proizvod")
            ;;
        esac
    done
}

function sastavi_sadrzaj_maila()
{
    sadrzaj="Pozdrav,\n\nProizvodi iz Konzuma:\n"
    brojac=0
    for proizvod in "${proizvodi_iz_Konzuma[@]}"
    do
        ((brojac++))
        proizvod=$(sed "s#--- Konzum##" <<<$proizvod)
        sadrzaj+="$brojac. $proizvod \n"
    done
    sadrzaj+="\nProizvodi iz Kauflanda:\n"
    brojac=0
    for proizvod in "${proizvodi_iz_Kauflanda[@]}"
    do
        ((brojac++))
        proizvod=$(sed "s#--- Kaufland##" <<<$proizvod)
        sadrzaj+="$brojac. $proizvod \n"
    done
}

function posalji_shopping_listu_na_mail()
{
    razdvoji_proizvode
    sastavi_sadrzaj_maila

    SENDGRID_API_KEY="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"
    EMAIL_TO=$1

    curl -X "POST" "https://api.sendgrid.com/v3/mail/send" \
        -H "Authorization: Bearer $SENDGRID_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{
                "personalizations": 
                [{ 
                    "to": [{ "email": "'"$EMAIL_TO"'" }],
                    "subject": "Shopping lista" 
                }],
                "from": 
                {
                    "email": "bibly.knjiznica@gmail.com"
                },
                "content": 
                [{
                    "type": "text/plain",
                    "value": "'"$sadrzaj"'"
                }]
            }'
}

while [ 1 ]
do
izbor=$(
	whiptail --title "GLAVNI IZBORNIK" --menu "\nOdaberi:" 12 25 3 \
    "1" "Proizvodi"   \
    "2" "YouTube"   \
	"9" "Izlaz"  3>&2 2>&1 1>&3	
)

case $izbor in
	"1")
        shopping_lista=()
        while [ 1 ]
        do
            izbor=$(
                whiptail --title "PROIZVODI" --menu "\nOdaberi:" 13 50 4 \
                "1" "Dodaj proizvod na shopping listu"   \
                "2" "Pregledaj shopping listu"   \
                "3" "Pošalji shopping listu na mail"   \
                "9" "Izlaz"  3>&2 2>&1 1>&3	
            )
            case $izbor in
	        "1")
                izbrisi_prethodno_dodane_proizvode
                unesi_kljucnu_rijec_pretrazivanja
                dohvati_podatke_proizvoda_iz_Konzuma_i_Kauflanda
                oblikuj_podatke_proizvoda_za_ispis
                sortiraj_proizvode_po_cijeni
                while [ 1 ]
                do
                    ispisi_proizvode "${sortirani_proizvodi[@]}"
                    if [ $exitstatus -eq 0 ]; then                
                        dodaj_odabrani_proizvod_u_kosaricu
                    else
                        break
                    fi
                done
            ;;
            "2")
                ispisi_proizvode "${shopping_lista[@]}"
            ;;
            "3")
                izbor=$(
                whiptail --title "POŠALJI MAIL" --menu "\nOdaberi:" 13 25 4 \
                "1" "zavrsnimarta@gmail.com"   \
                "2" "Unesi novi mail"   \
                "9" "Izlaz"  3>&2 2>&1 1>&3	
                )
                case $izbor in
                "1")
                    posalji_shopping_listu_na_mail "zavrsnimarta@gmail.com"
                ;;
                "2")
                    mail=$(whiptail --inputbox "\nUnesi mail:" 10 30 --title "UNOS MAILA" 3>&1 1>&2 2>&3)
                    posalji_shopping_listu_na_mail "$mail"
                ;;
                "9") 
                    break
                ;;
                esac
            ;;
            "9")
                break
            ;;
            esac
        done
    ;;
    "2")
        #TO DO
    ;;
    "9") 
        exit
    ;;
esac
done
exit
